/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package patientroomreserve;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import static patientroomreserve.Main.db;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 90554
 */
public class Start extends javax.swing.JFrame {

    static Connection con;

    public Start() {
        initComponents();
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            System.out.println("connected");
        } catch (SQLException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signInBttn = new javax.swing.JButton();
        signUpBttn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSignInUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSignInPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSignUpFirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSignUpUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSignUpLastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSignUpPassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signInBttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signInBttn.setForeground(new java.awt.Color(57, 57, 160));
        signInBttn.setText("Sign In");
        signInBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInBttnActionPerformed(evt);
            }
        });

        signUpBttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signUpBttn.setForeground(new java.awt.Color(57, 57, 160));
        signUpBttn.setText("Sign Up");
        signUpBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBttnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 57, 160));
        jLabel1.setText("Username");

        txtSignInUsername.setBackground(new java.awt.Color(192, 212, 232));
        txtSignInUsername.setFont(new java.awt.Font("Segoe UI Light", 2, 12)); // NOI18N
        txtSignInUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignInUsernameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 57, 160));
        jLabel2.setText("Password");

        txtSignInPassword.setBackground(new java.awt.Color(192, 212, 232));
        txtSignInPassword.setFont(new java.awt.Font("Segoe UI Light", 2, 12)); // NOI18N
        txtSignInPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignInPasswordActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(57, 57, 160));
        jLabel3.setText("First Name");

        txtSignUpFirstName.setBackground(new java.awt.Color(192, 212, 232));
        txtSignUpFirstName.setFont(new java.awt.Font("Segoe UI Light", 2, 12)); // NOI18N
        txtSignUpFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignUpFirstNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(57, 57, 160));
        jLabel4.setText("Username");

        txtSignUpUsername.setBackground(new java.awt.Color(192, 212, 232));
        txtSignUpUsername.setFont(new java.awt.Font("Segoe UI Light", 2, 12)); // NOI18N
        txtSignUpUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignUpUsernameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(57, 57, 160));
        jLabel5.setText("Last Name");

        txtSignUpLastName.setBackground(new java.awt.Color(192, 212, 232));
        txtSignUpLastName.setFont(new java.awt.Font("Segoe UI Light", 2, 12)); // NOI18N
        txtSignUpLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignUpLastNameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(57, 57, 160));
        jLabel6.setText("Password");

        txtSignUpPassword.setBackground(new java.awt.Color(192, 212, 232));
        txtSignUpPassword.setFont(new java.awt.Font("Segoe UI Light", 2, 12)); // NOI18N
        txtSignUpPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignUpPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(signInBttn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSignInUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSignInPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSignUpFirstName)
                            .addComponent(txtSignUpUsername)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txtSignUpPassword)
                            .addComponent(txtSignUpLastName)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(signUpBttn)))
                .addGap(0, 64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSignUpLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSignUpFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addComponent(txtSignInUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSignUpUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSignInPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSignUpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpBttn)
                    .addComponent(signInBttn)
                    .addComponent(jLabel7))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBttnActionPerformed

        System.out.println("con:::");
        System.out.println(con);
        System.out.println("::con:::");

        int i = 0;
        for (User u : db.userList) {
            if (u.getUsername().equals(txtSignUpUsername.getText())) {
                jLabel7.setText("Sorry, this username is taken.");
                break;
            } else {
                i++;
            }
        }

        if (i == db.userList.size()) {
            if (txtSignUpFirstName.getText().length() > 0 && txtSignUpLastName.getText().length() > 0 && txtSignUpUsername.getText().length() > 0 && txtSignUpPassword.getText().length() > 0) {
                User u = new User(txtSignUpFirstName.getText(), txtSignUpLastName.getText(), txtSignUpUsername.getText(), txtSignUpPassword.getText());
                db.userList.add(u);
                jLabel7.setText("Signed up!");
                addUserData();
                writeFile(txtSignUpUsername.getText(), txtSignUpFirstName.getText(), txtSignUpLastName.getText());
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Fill all the blanks.", "Dialog", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_signUpBttnActionPerformed

    private void signInBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInBttnActionPerformed
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("com.mycompany_PatientRoomReservation_jar_1.0-SNAPSHOTPU");
        EntityManager em = emf.createEntityManager();
        Users u = em.find(Users.class, txtSignInUsername.getText());

        if (u != null && u.getPassword().equals(txtSignInPassword.getText())) {
            Menu m = new Menu(txtSignInUsername.getText());
            m.setVisible(true);
            this.dispose();
        }else if(u==null) {
            JOptionPane.showMessageDialog(new JFrame(), "No user is found.", "Dialog", JOptionPane.ERROR_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(new JFrame(), "Wrong username/password.", "Dialog", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_signInBttnActionPerformed

    private void txtSignInUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignInUsernameActionPerformed

    }//GEN-LAST:event_txtSignInUsernameActionPerformed

    private void txtSignInPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignInPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSignInPasswordActionPerformed

    private void txtSignUpFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignUpFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSignUpFirstNameActionPerformed

    private void txtSignUpUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignUpUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSignUpUsernameActionPerformed

    private void txtSignUpPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignUpPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSignUpPasswordActionPerformed

    private void txtSignUpLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignUpLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSignUpLastNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    public void addUserData() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("com.mycompany_PatientRoomReservation_jar_1.0-SNAPSHOTPU");
        EntityManager em = emf.createEntityManager();
        try {
            em.getTransaction().begin();
            Users u = new Users();
            u.setUsername(txtSignUpUsername.getText());
            u.setFirstName(txtSignUpFirstName.getText());
            u.setLastName(txtSignUpLastName.getText());
            u.setPassword(txtSignUpPassword.getText());
            em.persist(u);
            em.getTransaction().commit();
        } catch (Exception e) {
            em.getTransaction().rollback();
        } finally {
            em.close();
            emf.close();
        }
    }
    
    public void writeFile(String username, String firstName, String lastName) {
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter("C:\\patientreservation\\user.txt", true));
            writer.newLine();
            writer.write(username + " " + firstName + " " + lastName);
            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton signInBttn;
    private javax.swing.JButton signUpBttn;
    private javax.swing.JTextField txtSignInPassword;
    private javax.swing.JTextField txtSignInUsername;
    private javax.swing.JTextField txtSignUpFirstName;
    private javax.swing.JTextField txtSignUpLastName;
    private javax.swing.JTextField txtSignUpPassword;
    private javax.swing.JTextField txtSignUpUsername;
    // End of variables declaration//GEN-END:variables
}
